# 关系型数据库配置
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:oracle:thin:@//192.168.70.245:1521/orcl
#    username: BS303INIT_TEST1008_03
#    password: BS303INIT_TEST1008_03
#    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:postgresql://101.35.80.154:5432/aixdb?stringtype=unspecified&currentSchema=aix
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver # 3.2.0开始支持SPI可省略此配置

